name: slurm_sweeps
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python>3.9.0
  - pytorch
  - pytorch-cuda=11.8
#  - cpuonly
  - torchvision
  - ipython
  - pip
  - pip:
      - -e .
      # for tests
      - pytest=7.3.1
      - fasteners
      - lightning
      - wandb
      # for development
      - pre_commit=3.3.1
