name: slurm_sweeps
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python>3.9.0
  - pytorch
#  - pytorch-cuda=11.8
  - cpuonly
  - torchvision
  - pip
  - pip:
      - -e .
      # for tests
      - pytest
      - pytest-cov
      - fasteners
      - lightning
      - wandb
      # for development
      - pre_commit
