name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ubuntu-latest
    # For the slurm action to work, you have to supply a mysql service as defined below.
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "8888:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Set up SLURM
        uses: koesterlab/setup-slurm-action@v1
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      - name: Install test dependencies
        run: |
          python -m pip install pytest pytest-cov
      - name: Running tests
        run: |
          pytest --cov=slurm_sweeps
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
